// Automatically generated by 'features/generate'.

// Check implied disabled features are not disabled.

#if defined(NBLOCK) && defined(NVIRTUAL)
#error "'NBLOCK' implies 'NVIRTUAL' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NBUMPREASONS)
#error "'NBUMP' implies 'NBUMPREASONS' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NINVERTED)
#error "'NBUMP' implies 'NINVERTED' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NRESTART)
#error "'NBUMP' implies 'NRESTART' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NREUSE)
#error "'NBUMP' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NREUSESTABLE)
#error "'NBUMP' implies 'NREUSESTABLE' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NSORTANALYZED)
#error "'NBUMP' implies 'NSORTANALYZED' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NVMTF)
#error "'NBUMP' implies 'NVMTF' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NVSIDS)
#error "'NBUMP' implies 'NVSIDS' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NBEST)
#error "'NCDCL' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NCHRONO)
#error "'NCDCL' implies 'NCHRONO' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NCHRONOREUSE)
#error "'NCDCL' implies 'NCHRONOREUSE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NFOCUSED)
#error "'NCDCL' implies 'NFOCUSED' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NGLUE)
#error "'NCDCL' implies 'NGLUE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NINPROCESSING)
#error "'NCDCL' implies 'NINPROCESSING' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NLEARN)
#error "'NCDCL' implies 'NLEARN' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NMINIMIZE)
#error "'NCDCL' implies 'NMINIMIZE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NREDUCE)
#error "'NCDCL' implies 'NREDUCE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NRESTART)
#error "'NCDCL' implies 'NRESTART' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NREUSE)
#error "'NCDCL' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NREUSESTABLE)
#error "'NCDCL' implies 'NREUSESTABLE' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NSHRINK)
#error "'NCDCL' implies 'NSHRINK' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NSORTANALYZED)
#error "'NCDCL' implies 'NSORTANALYZED' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NSORTDEDUCED)
#error "'NCDCL' implies 'NSORTDEDUCED' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NTIER1)
#error "'NCDCL' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NTIER2)
#error "'NCDCL' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NUSED)
#error "'NCDCL' implies 'NUSED' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NVMTF)
#error "'NCDCL' implies 'NVMTF' (the latter should not be defined)"
#endif
#if defined(NCDCL) && defined(NVSIDS)
#error "'NCDCL' implies 'NVSIDS' (the latter should not be defined)"
#endif
#if defined(NCHRONO) && defined(NCHRONOREUSE)
#error "'NCHRONO' implies 'NCHRONOREUSE' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NCHRONO)
#error "'NCONTROL' implies 'NCHRONO' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NCHRONOREUSE)
#error "'NCONTROL' implies 'NCHRONOREUSE' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NSHRINK)
#error "'NCONTROL' implies 'NSHRINK' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NVIVIFICATION)
#error "'NCONTROL' implies 'NVIVIFICATION' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NVIVIFICATIONLIMITS)
#error "'NCONTROL' implies 'NVIVIFICATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NCONTROL) && defined(NVIVIFYIMPLY)
#error "'NCONTROL' implies 'NVIVIFYIMPLY' (the latter should not be defined)"
#endif
#if defined(NELIMINATION) && defined(NELIMINATIONLIMITS)
#error "'NELIMINATION' implies 'NELIMINATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NELIMINATION) && defined(NSTRENGTHENING)
#error "'NELIMINATION' implies 'NSTRENGTHENING' (the latter should not be defined)"
#endif
#if defined(NELIMINATION) && defined(NSUBSUMPTION)
#error "'NELIMINATION' implies 'NSUBSUMPTION' (the latter should not be defined)"
#endif
#if defined(NELIMINATION) && defined(NSUBSUMPTIONLIMITS)
#error "'NELIMINATION' implies 'NSUBSUMPTIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NGLUE) && defined(NTIER1)
#error "'NGLUE' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NGLUE) && defined(NTIER2)
#error "'NGLUE' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NGLUE)
#error "'NLEARN' implies 'NGLUE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NINPROCESSING)
#error "'NLEARN' implies 'NINPROCESSING' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NMINIMIZE)
#error "'NLEARN' implies 'NMINIMIZE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NREDUCE)
#error "'NLEARN' implies 'NREDUCE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NRESTART)
#error "'NLEARN' implies 'NRESTART' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NREUSE)
#error "'NLEARN' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NREUSESTABLE)
#error "'NLEARN' implies 'NREUSESTABLE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NSHRINK)
#error "'NLEARN' implies 'NSHRINK' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NSORTDEDUCED)
#error "'NLEARN' implies 'NSORTDEDUCED' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NTIER1)
#error "'NLEARN' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NTIER2)
#error "'NLEARN' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NUSED)
#error "'NLEARN' implies 'NUSED' (the latter should not be defined)"
#endif
#if defined(NLIMITS) && defined(NELIMINATIONLIMITS)
#error "'NLIMITS' implies 'NELIMINATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NLIMITS) && defined(NSUBSUMPTIONLIMITS)
#error "'NLIMITS' implies 'NSUBSUMPTIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NMINIMIZE) && defined(NSHRINK)
#error "'NMINIMIZE' implies 'NSHRINK' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NGLUE)
#error "'NREDUCE' implies 'NGLUE' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NTIER1)
#error "'NREDUCE' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NTIER2)
#error "'NREDUCE' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NUSED)
#error "'NREDUCE' implies 'NUSED' (the latter should not be defined)"
#endif
#if defined(NREPHASE) && defined(NBEST)
#error "'NREPHASE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NREPHASE) && defined(NINVERTED)
#error "'NREPHASE' implies 'NINVERTED' (the latter should not be defined)"
#endif
#if defined(NRESTART) && defined(NREUSE)
#error "'NRESTART' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NRESTART) && defined(NREUSESTABLE)
#error "'NRESTART' implies 'NREUSESTABLE' (the latter should not be defined)"
#endif
#if defined(NREUSE) && defined(NREUSESTABLE)
#error "'NREUSE' implies 'NREUSESTABLE' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NBEST)
#error "'NSAVE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NINVERTED)
#error "'NSAVE' implies 'NINVERTED' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NREPHASE)
#error "'NSAVE' implies 'NREPHASE' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NELIMINATION)
#error "'NSIMPLIFICATION' implies 'NELIMINATION' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NELIMINATIONLIMITS)
#error "'NSIMPLIFICATION' implies 'NELIMINATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NINPROCESSING)
#error "'NSIMPLIFICATION' implies 'NINPROCESSING' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NSTRENGTHENING)
#error "'NSIMPLIFICATION' implies 'NSTRENGTHENING' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NSUBSUMPTION)
#error "'NSIMPLIFICATION' implies 'NSUBSUMPTION' (the latter should not be defined)"
#endif
#if defined(NSIMPLIFICATION) && defined(NSUBSUMPTIONLIMITS)
#error "'NSIMPLIFICATION' implies 'NSUBSUMPTIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NSORTDEDUCED) && defined(NSHRINK)
#error "'NSORTDEDUCED' implies 'NSHRINK' (the latter should not be defined)"
#endif
#if defined(NSTABLE) && defined(NBEST)
#error "'NSTABLE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NSTABLE) && defined(NTARGET)
#error "'NSTABLE' implies 'NTARGET' (the latter should not be defined)"
#endif
#if defined(NSUBSUMPTION) && defined(NSTRENGTHENING)
#error "'NSUBSUMPTION' implies 'NSTRENGTHENING' (the latter should not be defined)"
#endif
#if defined(NSUBSUMPTION) && defined(NSUBSUMPTIONLIMITS)
#error "'NSUBSUMPTION' implies 'NSUBSUMPTIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NTARGET) && defined(NBEST)
#error "'NTARGET' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NTIER1) && defined(NTIER2)
#error "'NTIER1' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NUSED) && defined(NTIER2)
#error "'NUSED' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NVIVIFICATION) && defined(NVIVIFICATIONLIMITS)
#error "'NVIVIFICATION' implies 'NVIVIFICATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NVIVIFICATION) && defined(NVIVIFYIMPLY)
#error "'NVIVIFICATION' implies 'NVIVIFYIMPLY' (the latter should not be defined)"
#endif
#if defined(NVMTF) && defined(NSORTANALYZED)
#error "'NVMTF' implies 'NSORTANALYZED' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NBLOCK)
#error "'NWATCHES' implies 'NBLOCK' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NCACHE)
#error "'NWATCHES' implies 'NCACHE' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NELIMINATION)
#error "'NWATCHES' implies 'NELIMINATION' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NELIMINATIONLIMITS)
#error "'NWATCHES' implies 'NELIMINATIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NSTRENGTHENING)
#error "'NWATCHES' implies 'NSTRENGTHENING' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NSUBSUMPTION)
#error "'NWATCHES' implies 'NSUBSUMPTION' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NSUBSUMPTIONLIMITS)
#error "'NWATCHES' implies 'NSUBSUMPTIONLIMITS' (the latter should not be defined)"
#endif
#if defined(NWATCHES) && defined(NVIRTUAL)
#error "'NWATCHES' implies 'NVIRTUAL' (the latter should not be defined)"
#endif

// Check clashing disabled features.

#if defined(NFOCUSED) && defined(NSTABLE)
#error "'NFOCUSED' and 'NSTABLE' can not be combined"
#endif
#if defined(NFOCUSED) && defined(NVMTF)
#error "'NFOCUSED' and 'NVMTF' can not be combined"
#endif
#if defined(NSTABLE) && defined(NVSIDS)
#error "'NSTABLE' and 'NVSIDS' can not be combined"
#endif
#if defined(NCDCL) && defined(NSTABLE)
#error "'NCDCL' and 'NSTABLE' can not be combined"
#endif
