// Automatically generated by 'features/generate'.

// Check implied disabled features are not disabled.

#if defined(NBLOCK) && defined(NVIRTUAL)
#error "'NBLOCK' implies 'NVIRTUAL' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NREASONS)
#error "'NBUMP' implies 'NREASONS' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NREUSE)
#error "'NBUMP' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NRSORT)
#error "'NBUMP' implies 'NRSORT' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NSORT)
#error "'NBUMP' implies 'NSORT' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NVMTF)
#error "'NBUMP' implies 'NVMTF' (the latter should not be defined)"
#endif
#if defined(NBUMP) && defined(NVSIDS)
#error "'NBUMP' implies 'NVSIDS' (the latter should not be defined)"
#endif
#if defined(NGLUE) && defined(NTIER1)
#error "'NGLUE' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NGLUE) && defined(NTIER2)
#error "'NGLUE' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NGLUE)
#error "'NLEARN' implies 'NGLUE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NMINIMIZE)
#error "'NLEARN' implies 'NMINIMIZE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NREDUCE)
#error "'NLEARN' implies 'NREDUCE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NRESTART)
#error "'NLEARN' implies 'NRESTART' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NREUSE)
#error "'NLEARN' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NTIER1)
#error "'NLEARN' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NTIER2)
#error "'NLEARN' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NLEARN) && defined(NUSED)
#error "'NLEARN' implies 'NUSED' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NGLUE)
#error "'NREDUCE' implies 'NGLUE' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NTIER1)
#error "'NREDUCE' implies 'NTIER1' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NTIER2)
#error "'NREDUCE' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NREDUCE) && defined(NUSED)
#error "'NREDUCE' implies 'NUSED' (the latter should not be defined)"
#endif
#if defined(NREPHASE) && defined(NBEST)
#error "'NREPHASE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NREPHASE) && defined(NINVERTED)
#error "'NREPHASE' implies 'NINVERTED' (the latter should not be defined)"
#endif
#if defined(NRESTART) && defined(NREUSE)
#error "'NRESTART' implies 'NREUSE' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NBEST)
#error "'NSAVE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NINVERTED)
#error "'NSAVE' implies 'NINVERTED' (the latter should not be defined)"
#endif
#if defined(NSAVE) && defined(NREPHASE)
#error "'NSAVE' implies 'NREPHASE' (the latter should not be defined)"
#endif
#if defined(NSORT) && defined(NRSORT)
#error "'NSORT' implies 'NRSORT' (the latter should not be defined)"
#endif
#if defined(NSTABLE) && defined(NBEST)
#error "'NSTABLE' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NSTABLE) && defined(NTARGET)
#error "'NSTABLE' implies 'NTARGET' (the latter should not be defined)"
#endif
#if defined(NTARGET) && defined(NBEST)
#error "'NTARGET' implies 'NBEST' (the latter should not be defined)"
#endif
#if defined(NTIER1) && defined(NTIER2)
#error "'NTIER1' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NUSED) && defined(NTIER2)
#error "'NUSED' implies 'NTIER2' (the latter should not be defined)"
#endif
#if defined(NVMTF) && defined(NRSORT)
#error "'NVMTF' implies 'NRSORT' (the latter should not be defined)"
#endif
#if defined(NVMTF) && defined(NSORT)
#error "'NVMTF' implies 'NSORT' (the latter should not be defined)"
#endif

// Check clashing disabled features.

#if defined(NFOCUSED) && defined(NSTABLE)
#error "'NFOCUSED' and 'NSTABLE' can not be combined"
#endif
#if defined(NFOCUSED) && defined(NVMTF)
#error "'NFOCUSED' and 'NVMTF' can not be combined"
#endif
#if defined(NSTABLE) && defined(NVSIDS)
#error "'NSTABLE' and 'NVSIDS' can not be combined"
#endif
#if defined(NVMTF) && defined(NVSIDS)
#error "'NVMTF' and 'NVSIDS' can not be combined"
#endif
