// Automatically generated by 'features/generate'.

// Print compile time diagnostics on disabled features.

#ifdef NBEST
#pragma message "#define NBEST"
#endif
#ifdef NBLOCK
#pragma message "#define NBLOCK"
#endif
#ifdef NBUMP
#pragma message "#define NBUMP"
#endif
#ifdef NBUMPREASONS
#pragma message "#define NBUMPREASONS"
#endif
#ifdef NCACHE
#pragma message "#define NCACHE"
#endif
#ifdef NCOLOR
#pragma message "#define NCOLOR"
#endif
#ifdef NELIMINATION
#pragma message "#define NELIMINATION"
#endif
#ifdef NELIMINATIONLIMITS
#pragma message "#define NELIMINATIONLIMITS"
#endif
#ifdef NFOCUSED
#pragma message "#define NFOCUSED"
#endif
#ifdef NGLUE
#pragma message "#define NGLUE"
#endif
#ifdef NINPROCESSING
#pragma message "#define NINPROCESSING"
#endif
#ifdef NINVERTED
#pragma message "#define NINVERTED"
#endif
#ifdef NLAZYACTIVATION
#pragma message "#define NLAZYACTIVATION"
#endif
#ifdef NLEARN
#pragma message "#define NLEARN"
#endif
#ifdef NLIMITS
#pragma message "#define NLIMITS"
#endif
#ifdef NMINIMIZE
#pragma message "#define NMINIMIZE"
#endif
#ifdef NRADIXSORT
#pragma message "#define NRADIXSORT"
#endif
#ifdef NREDUCE
#pragma message "#define NREDUCE"
#endif
#ifdef NREPHASE
#pragma message "#define NREPHASE"
#endif
#ifdef NRESTART
#pragma message "#define NRESTART"
#endif
#ifdef NREUSE
#pragma message "#define NREUSE"
#endif
#ifdef NREUSESTABLE
#pragma message "#define NREUSESTABLE"
#endif
#ifdef NSAVE
#pragma message "#define NSAVE"
#endif
#ifdef NSHRINK
#pragma message "#define NSHRINK"
#endif
#ifdef NSIMPLIFICATION
#pragma message "#define NSIMPLIFICATION"
#endif
#ifdef NSORTANALYZED
#pragma message "#define NSORTANALYZED"
#endif
#ifdef NSORTDEDUCED
#pragma message "#define NSORTDEDUCED"
#endif
#ifdef NSTABLE
#pragma message "#define NSTABLE"
#endif
#ifdef NSTRENGTHENING
#pragma message "#define NSTRENGTHENING"
#endif
#ifdef NSUBSUMPTION
#pragma message "#define NSUBSUMPTION"
#endif
#ifdef NSUBSUMPTIONLIMITS
#pragma message "#define NSUBSUMPTIONLIMITS"
#endif
#ifdef NTARGET
#pragma message "#define NTARGET"
#endif
#ifdef NTIER1
#pragma message "#define NTIER1"
#endif
#ifdef NTIER2
#pragma message "#define NTIER2"
#endif
#ifdef NTRUE
#pragma message "#define NTRUE"
#endif
#ifdef NUSED
#pragma message "#define NUSED"
#endif
#ifdef NVARIADIC
#pragma message "#define NVARIADIC"
#endif
#ifdef NVIRTUAL
#pragma message "#define NVIRTUAL"
#endif
#ifdef NVMTF
#pragma message "#define NVMTF"
#endif
#ifdef NVSIDS
#pragma message "#define NVSIDS"
#endif
#ifdef NWATCHES
#pragma message "#define NWATCHES"
#endif
