// Automatically generated by 'features/generate'.

// Print compile time diagnostics on disabled features.

#ifdef NACTIVE
#pragma message "#define NACTIVE"
#endif
#ifdef NBEST
#pragma message "#define NBEST"
#endif
#ifdef NBLOCK
#pragma message "#define NBLOCK"
#endif
#ifdef NBUMP
#pragma message "#define NBUMP"
#endif
#ifdef NCACHE
#pragma message "#define NCACHE"
#endif
#ifdef NCOLOR
#pragma message "#define NCOLOR"
#endif
#ifdef NFOCUSED
#pragma message "#define NFOCUSED"
#endif
#ifdef NGLUE
#pragma message "#define NGLUE"
#endif
#ifdef NINVERTED
#pragma message "#define NINVERTED"
#endif
#ifdef NLEARN
#pragma message "#define NLEARN"
#endif
#ifdef NMINIMIZE
#pragma message "#define NMINIMIZE"
#endif
#ifdef NREASONS
#pragma message "#define NREASONS"
#endif
#ifdef NREDUCE
#pragma message "#define NREDUCE"
#endif
#ifdef NREPHASE
#pragma message "#define NREPHASE"
#endif
#ifdef NRESTART
#pragma message "#define NRESTART"
#endif
#ifdef NRSORT
#pragma message "#define NRSORT"
#endif
#ifdef NSAVE
#pragma message "#define NSAVE"
#endif
#ifdef NSORT
#pragma message "#define NSORT"
#endif
#ifdef NSTABLE
#pragma message "#define NSTABLE"
#endif
#ifdef NTARGET
#pragma message "#define NTARGET"
#endif
#ifdef NTIER1
#pragma message "#define NTIER1"
#endif
#ifdef NTIER2
#pragma message "#define NTIER2"
#endif
#ifdef NTRUE
#pragma message "#define NTRUE"
#endif
#ifdef NUSED
#pragma message "#define NUSED"
#endif
#ifdef NVARIADIC
#pragma message "#define NVARIADIC"
#endif
#ifdef NVIRTUAL
#pragma message "#define NVIRTUAL"
#endif
#ifdef NVMTF
#pragma message "#define NVMTF"
#endif
#ifdef NVSIDS
#pragma message "#define NVSIDS"
#endif
