// Automatically generated by 'features/generate'.

// Force implied disabled features to be disabled.

#if defined(NBLOCK) && !defined(NVIRTUAL)
#define NVIRTUAL
#endif
#if defined(NBUMP) && !defined(NBUMPREASONS)
#define NBUMPREASONS
#endif
#if defined(NBUMP) && !defined(NINVERTED)
#define NINVERTED
#endif
#if defined(NBUMP) && !defined(NRESTART)
#define NRESTART
#endif
#if defined(NBUMP) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NBUMP) && !defined(NREUSESTABLE)
#define NREUSESTABLE
#endif
#if defined(NBUMP) && !defined(NSORTANALYZED)
#define NSORTANALYZED
#endif
#if defined(NBUMP) && !defined(NVMTF)
#define NVMTF
#endif
#if defined(NBUMP) && !defined(NVSIDS)
#define NVSIDS
#endif
#if defined(NCDCL) && !defined(NBEST)
#define NBEST
#endif
#if defined(NCDCL) && !defined(NCHRONO)
#define NCHRONO
#endif
#if defined(NCDCL) && !defined(NCHRONOREUSE)
#define NCHRONOREUSE
#endif
#if defined(NCDCL) && !defined(NFOCUSED)
#define NFOCUSED
#endif
#if defined(NCDCL) && !defined(NGLUE)
#define NGLUE
#endif
#if defined(NCDCL) && !defined(NINPROCESSING)
#define NINPROCESSING
#endif
#if defined(NCDCL) && !defined(NLEARN)
#define NLEARN
#endif
#if defined(NCDCL) && !defined(NMINIMIZE)
#define NMINIMIZE
#endif
#if defined(NCDCL) && !defined(NREDUCE)
#define NREDUCE
#endif
#if defined(NCDCL) && !defined(NRESTART)
#define NRESTART
#endif
#if defined(NCDCL) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NCDCL) && !defined(NREUSESTABLE)
#define NREUSESTABLE
#endif
#if defined(NCDCL) && !defined(NSHRINK)
#define NSHRINK
#endif
#if defined(NCDCL) && !defined(NSORTANALYZED)
#define NSORTANALYZED
#endif
#if defined(NCDCL) && !defined(NSORTDEDUCED)
#define NSORTDEDUCED
#endif
#if defined(NCDCL) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NCDCL) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NCDCL) && !defined(NUSED)
#define NUSED
#endif
#if defined(NCDCL) && !defined(NVMTF)
#define NVMTF
#endif
#if defined(NCDCL) && !defined(NVSIDS)
#define NVSIDS
#endif
#if defined(NCHRONO) && !defined(NCHRONOREUSE)
#define NCHRONOREUSE
#endif
#if defined(NCONTROL) && !defined(NCHRONO)
#define NCHRONO
#endif
#if defined(NCONTROL) && !defined(NCHRONOREUSE)
#define NCHRONOREUSE
#endif
#if defined(NCONTROL) && !defined(NSHRINK)
#define NSHRINK
#endif
#if defined(NCONTROL) && !defined(NVIVIFICATION)
#define NVIVIFICATION
#endif
#if defined(NCONTROL) && !defined(NVIVIFICATIONLIMITS)
#define NVIVIFICATIONLIMITS
#endif
#if defined(NCONTROL) && !defined(NVIVIFYIMPLY)
#define NVIVIFYIMPLY
#endif
#if defined(NELIMINATION) && !defined(NELIMINATIONLIMITS)
#define NELIMINATIONLIMITS
#endif
#if defined(NELIMINATION) && !defined(NSTRENGTHENING)
#define NSTRENGTHENING
#endif
#if defined(NELIMINATION) && !defined(NSUBSUMPTION)
#define NSUBSUMPTION
#endif
#if defined(NELIMINATION) && !defined(NSUBSUMPTIONLIMITS)
#define NSUBSUMPTIONLIMITS
#endif
#if defined(NGLUE) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NGLUE) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NLEARN) && !defined(NGLUE)
#define NGLUE
#endif
#if defined(NLEARN) && !defined(NINPROCESSING)
#define NINPROCESSING
#endif
#if defined(NLEARN) && !defined(NMINIMIZE)
#define NMINIMIZE
#endif
#if defined(NLEARN) && !defined(NREDUCE)
#define NREDUCE
#endif
#if defined(NLEARN) && !defined(NRESTART)
#define NRESTART
#endif
#if defined(NLEARN) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NLEARN) && !defined(NREUSESTABLE)
#define NREUSESTABLE
#endif
#if defined(NLEARN) && !defined(NSHRINK)
#define NSHRINK
#endif
#if defined(NLEARN) && !defined(NSORTDEDUCED)
#define NSORTDEDUCED
#endif
#if defined(NLEARN) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NLEARN) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NLEARN) && !defined(NUSED)
#define NUSED
#endif
#if defined(NLIMITS) && !defined(NELIMINATIONLIMITS)
#define NELIMINATIONLIMITS
#endif
#if defined(NLIMITS) && !defined(NSUBSUMPTIONLIMITS)
#define NSUBSUMPTIONLIMITS
#endif
#if defined(NMINIMIZE) && !defined(NSHRINK)
#define NSHRINK
#endif
#if defined(NREDUCE) && !defined(NGLUE)
#define NGLUE
#endif
#if defined(NREDUCE) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NREDUCE) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NREDUCE) && !defined(NUSED)
#define NUSED
#endif
#if defined(NREPHASE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NREPHASE) && !defined(NINVERTED)
#define NINVERTED
#endif
#if defined(NRESTART) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NRESTART) && !defined(NREUSESTABLE)
#define NREUSESTABLE
#endif
#if defined(NREUSE) && !defined(NREUSESTABLE)
#define NREUSESTABLE
#endif
#if defined(NSAVE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NSAVE) && !defined(NINVERTED)
#define NINVERTED
#endif
#if defined(NSAVE) && !defined(NREPHASE)
#define NREPHASE
#endif
#if defined(NSIMPLIFICATION) && !defined(NELIMINATION)
#define NELIMINATION
#endif
#if defined(NSIMPLIFICATION) && !defined(NELIMINATIONLIMITS)
#define NELIMINATIONLIMITS
#endif
#if defined(NSIMPLIFICATION) && !defined(NINPROCESSING)
#define NINPROCESSING
#endif
#if defined(NSIMPLIFICATION) && !defined(NSTRENGTHENING)
#define NSTRENGTHENING
#endif
#if defined(NSIMPLIFICATION) && !defined(NSUBSUMPTION)
#define NSUBSUMPTION
#endif
#if defined(NSIMPLIFICATION) && !defined(NSUBSUMPTIONLIMITS)
#define NSUBSUMPTIONLIMITS
#endif
#if defined(NSORTDEDUCED) && !defined(NSHRINK)
#define NSHRINK
#endif
#if defined(NSTABLE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NSTABLE) && !defined(NTARGET)
#define NTARGET
#endif
#if defined(NSUBSUMPTION) && !defined(NSTRENGTHENING)
#define NSTRENGTHENING
#endif
#if defined(NSUBSUMPTION) && !defined(NSUBSUMPTIONLIMITS)
#define NSUBSUMPTIONLIMITS
#endif
#if defined(NTARGET) && !defined(NBEST)
#define NBEST
#endif
#if defined(NTIER1) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NUSED) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NVIVIFICATION) && !defined(NVIVIFICATIONLIMITS)
#define NVIVIFICATIONLIMITS
#endif
#if defined(NVIVIFICATION) && !defined(NVIVIFYIMPLY)
#define NVIVIFYIMPLY
#endif
#if defined(NVMTF) && !defined(NSORTANALYZED)
#define NSORTANALYZED
#endif
#if defined(NWATCHES) && !defined(NBLOCK)
#define NBLOCK
#endif
#if defined(NWATCHES) && !defined(NCACHE)
#define NCACHE
#endif
#if defined(NWATCHES) && !defined(NELIMINATION)
#define NELIMINATION
#endif
#if defined(NWATCHES) && !defined(NELIMINATIONLIMITS)
#define NELIMINATIONLIMITS
#endif
#if defined(NWATCHES) && !defined(NSTRENGTHENING)
#define NSTRENGTHENING
#endif
#if defined(NWATCHES) && !defined(NSUBSUMPTION)
#define NSUBSUMPTION
#endif
#if defined(NWATCHES) && !defined(NSUBSUMPTIONLIMITS)
#define NSUBSUMPTIONLIMITS
#endif
#if defined(NWATCHES) && !defined(NVIRTUAL)
#define NVIRTUAL
#endif
