# Automatically generated by 'features/generate'.

# Initialize all features to be enabled by default.

best=yes
block=yes
bump=yes
bumpreasons=yes
cache=yes
color=yes
elimination=yes
eliminationlimits=yes
focused=yes
glue=yes
inprocessing=yes
inverted=yes
lazyactivation=yes
learn=yes
limits=yes
minimize=yes
radixsort=yes
reduce=yes
rephase=yes
restart=yes
reuse=yes
reusestable=yes
save=yes
shrink=yes
simplification=yes
sortanalyzed=yes
sortdeduced=yes
stable=yes
strengthening=yes
subsumption=yes
subsumptionlimits=yes
target=yes
tier1=yes
tier2=yes
true=yes
used=yes
variadic=yes
virtual=yes
vmtf=yes
vsids=yes
watches=yes
