// Automatically generated by 'features/generate'.

// Force implied disabled features to be disabled.

#if defined(NBLOCK) && !defined(NVIRTUAL)
#define NVIRTUAL
#endif
#if defined(NBUMP) && !defined(NREASONS)
#define NREASONS
#endif
#if defined(NBUMP) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NBUMP) && !defined(NRSORT)
#define NRSORT
#endif
#if defined(NBUMP) && !defined(NSORT)
#define NSORT
#endif
#if defined(NBUMP) && !defined(NVMTF)
#define NVMTF
#endif
#if defined(NBUMP) && !defined(NVSIDS)
#define NVSIDS
#endif
#if defined(NGLUE) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NGLUE) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NLEARN) && !defined(NGLUE)
#define NGLUE
#endif
#if defined(NLEARN) && !defined(NMINIMIZE)
#define NMINIMIZE
#endif
#if defined(NLEARN) && !defined(NREDUCE)
#define NREDUCE
#endif
#if defined(NLEARN) && !defined(NRESTART)
#define NRESTART
#endif
#if defined(NLEARN) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NLEARN) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NLEARN) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NLEARN) && !defined(NUSED)
#define NUSED
#endif
#if defined(NREDUCE) && !defined(NGLUE)
#define NGLUE
#endif
#if defined(NREDUCE) && !defined(NTIER1)
#define NTIER1
#endif
#if defined(NREDUCE) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NREDUCE) && !defined(NUSED)
#define NUSED
#endif
#if defined(NREPHASE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NREPHASE) && !defined(NINVERTED)
#define NINVERTED
#endif
#if defined(NRESTART) && !defined(NREUSE)
#define NREUSE
#endif
#if defined(NSAVE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NSAVE) && !defined(NINVERTED)
#define NINVERTED
#endif
#if defined(NSAVE) && !defined(NREPHASE)
#define NREPHASE
#endif
#if defined(NSORT) && !defined(NRSORT)
#define NRSORT
#endif
#if defined(NSTABLE) && !defined(NBEST)
#define NBEST
#endif
#if defined(NSTABLE) && !defined(NTARGET)
#define NTARGET
#endif
#if defined(NTARGET) && !defined(NBEST)
#define NBEST
#endif
#if defined(NTIER1) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NUSED) && !defined(NTIER2)
#define NTIER2
#endif
#if defined(NVMTF) && !defined(NRSORT)
#define NRSORT
#endif
#if defined(NVMTF) && !defined(NSORT)
#define NSORT
#endif
