# Automatically generated by 'features/generate'.

# Initialize all features to be enabled by default.

active=yes
best=yes
block=yes
bump=yes
cache=yes
color=yes
focused=yes
glue=yes
inverted=yes
learn=yes
minimize=yes
reasons=yes
reduce=yes
rephase=yes
restart=yes
reuse=yes
rsort=yes
save=yes
sort=yes
stable=yes
target=yes
tier1=yes
tier2=yes
true=yes
used=yes
variadic=yes
virtual=yes
vmtf=yes
vsids=yes
