# Automatically generated by 'features/generate'.

# Match options which disable features.

parse () {
  res=0
  case x"$1" in
    x"--no-active") active=no;;
    x"--no-best") best=no;;
    x"--no-block") block=no;;
    x"--no-bump") bump=no;;
    x"--no-cache") cache=no;;
    x"--no-focused") focused=no;;
    x"--no-glue") glue=no;;
    x"--no-inverted") inverted=no;;
    x"--no-learn") learn=no;;
    x"--no-minimize") minimize=no;;
    x"--no-reasons") reasons=no;;
    x"--no-reduce") reduce=no;;
    x"--no-rephase") rephase=no;;
    x"--no-restart") restart=no;;
    x"--no-save") save=no;;
    x"--no-sort") sort=no;;
    x"--no-stable") stable=no;;
    x"--no-target") target=no;;
    x"--no-tier1") tier1=no;;
    x"--no-tier2") tier2=no;;
    x"--no-true") true=no;;
    x"--no-used") used=no;;
    x"--no-variadic") variadic=no;;
    x"--no-virtual") virtual=no;;
    x"--no-vmtf") vmtf=no;;
    x"--no-vsids") vsids=no;;
    *) res=1;;
  esac
  return $res
}
