// Automatically generated by 'features/generate'.

// Version extension string for disabled features.

#ifdef NACTIVE
"-active"
#endif
#ifdef NBEST
"-best"
#endif
#ifdef NBLOCK
"-block"
#endif
#ifdef NBUMP
"-bump"
#endif
#ifdef NCACHE
"-cache"
#endif
#ifdef NCOLOR
"-color"
#endif
#ifdef NFOCUSED
"-focused"
#endif
#ifdef NGLUE
"-glue"
#endif
#ifdef NINVERTED
"-inverted"
#endif
#ifdef NLEARN
"-learn"
#endif
#ifdef NMINIMIZE
"-minimize"
#endif
#ifdef NREASONS
"-reasons"
#endif
#ifdef NREDUCE
"-reduce"
#endif
#ifdef NREPHASE
"-rephase"
#endif
#ifdef NRESTART
"-restart"
#endif
#ifdef NREUSE
"-reuse"
#endif
#ifdef NRSORT
"-rsort"
#endif
#ifdef NSAVE
"-save"
#endif
#ifdef NSORT
"-sort"
#endif
#ifdef NSTABLE
"-stable"
#endif
#ifdef NTARGET
"-target"
#endif
#ifdef NTIER1
"-tier1"
#endif
#ifdef NTIER2
"-tier2"
#endif
#ifdef NTRUE
"-true"
#endif
#ifdef NUSED
"-used"
#endif
#ifdef NVARIADIC
"-variadic"
#endif
#ifdef NVIRTUAL
"-virtual"
#endif
#ifdef NVMTF
"-vmtf"
#endif
#ifdef NVSIDS
"-vsids"
#endif
