// Automatically generated by 'features/generate'.

// Version extension string for disabled features.

#ifdef NBEST
"-best"
#endif
#ifdef NBLOCK
"-block"
#endif
#ifdef NBUMP
"-bump"
#endif
#ifdef NBUMPREASONS
"-bumpreasons"
#endif
#ifdef NCACHE
"-cache"
#endif
#ifdef NCDCL
"-cdcl"
#endif
#ifdef NCHEAPPROFILING
"-cheapprofiling"
#endif
#ifdef NCHRONO
"-chrono"
#endif
#ifdef NCHRONOREUSE
"-chronoreuse"
#endif
#ifdef NCOLOR
"-color"
#endif
#ifdef NCONTROL
"-control"
#endif
#ifdef NELIMINATION
"-elimination"
#endif
#ifdef NELIMINATIONLIMITS
"-eliminationlimits"
#endif
#ifdef NFOCUSED
"-focused"
#endif
#ifdef NGLUE
"-glue"
#endif
#ifdef NINPROCESSING
"-inprocessing"
#endif
#ifdef NINVERTED
"-inverted"
#endif
#ifdef NLAZYACTIVATION
"-lazyactivation"
#endif
#ifdef NLEARN
"-learn"
#endif
#ifdef NLIMITS
"-limits"
#endif
#ifdef NMINIMIZE
"-minimize"
#endif
#ifdef NRADIXSORT
"-radixsort"
#endif
#ifdef NREDUCE
"-reduce"
#endif
#ifdef NREPHASE
"-rephase"
#endif
#ifdef NRESTART
"-restart"
#endif
#ifdef NREUSE
"-reuse"
#endif
#ifdef NREUSESTABLE
"-reusestable"
#endif
#ifdef NSAVE
"-save"
#endif
#ifdef NSHRINK
"-shrink"
#endif
#ifdef NSIMPLIFICATION
"-simplification"
#endif
#ifdef NSORTANALYZED
"-sortanalyzed"
#endif
#ifdef NSORTDEDUCED
"-sortdeduced"
#endif
#ifdef NSTABLE
"-stable"
#endif
#ifdef NSTRENGTHENING
"-strengthening"
#endif
#ifdef NSUBSUMPTION
"-subsumption"
#endif
#ifdef NSUBSUMPTIONLIMITS
"-subsumptionlimits"
#endif
#ifdef NTARGET
"-target"
#endif
#ifdef NTIER1
"-tier1"
#endif
#ifdef NTIER2
"-tier2"
#endif
#ifdef NTRUE
"-true"
#endif
#ifdef NUSED
"-used"
#endif
#ifdef NVARIADIC
"-variadic"
#endif
#ifdef NVIRTUAL
"-virtual"
#endif
#ifdef NVIVIFICATION
"-vivification"
#endif
#ifdef NVIVIFICATIONLIMITS
"-vivificationlimits"
#endif
#ifdef NVIVIFYIMPLY
"-vivifyimply"
#endif
#ifdef NVMTF
"-vmtf"
#endif
#ifdef NVSIDS
"-vsids"
#endif
#ifdef NWATCHES
"-watches"
#endif
